#
#  This file contains all the defaults that it will be used when the application is started.
#  There are two main sections: SpringBoot Config and  Application Config
#

#
# SpringBoot Config: WiseMapping Backend is based on SpringBoot. Additional configurations documentation could be found https://docs.spring.io/spring-boot/3.3/reference/features/external-config.html.
#
spring:
  # SMTP server configuration used for password recovery and notifications.
  mail:
    host: smtp.example.com
    port: 25
    username: setusername
    password: setpassword
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  # Database configuration options. Examples can be found: https://github.com/wisemapping/wisemapping-open-source/tree/develop/config/database
  datasource:
    url: jdbc:hsqldb:mem:wisemapping
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    password: ''
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        current_session_context_class: thread
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      platform: hsqldb
  # General Config: Do no touch.
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: always
  application:
    name: wisemapping-api
    title: wisemapping-api


#
# Log Level
#
logging:
  level:
    org:
      apache:
        tomcat: INFO
    root: INFO

#
# Application Config related options:
#
app:
  # This information is mainly used by the frontend to connect to the backend. It must match the deployment topology used.
  site:
    ui-base-url: http://localhost
    api-base-url: http://localhost
  # Enable API basic authentication.
  api:
    http-basic-enabled: false
  # JSON Web Token configuration options. Secret must be configured.
  jwt:
    secret: dlqxKAg685SaKhsQXIMeM=JWCw3bkl3Ei3Tb7LMlnd19oMd66burPNlJ0Po1qguyjgpakQTk2CN3
    expirationMin: 10080 # One week
  # Admin account with super admin permissions on the API.
  admin:
    user: admin@wisemapping.org
  # STMP email configurations
  mail:
    sender-email: root@localhost
    support-email: root@localhost
    enabled: false
  accounts:
    max-inactive: 20
  # Google OAuth Authentication
  security:
    #    corsAllowedOrigins: https://dev.wisemapping.com
    oauth2:
      google:
        clientSecret: <google-oath>
        confirmUrl: https://oauth2.googleapis.com/token
        userinfoUrl: https://www:googleapis.com/oauth2/v3/userinfo
        callbackUrl: https://app.wisemapping.com/c/registration-google
        clientId: 625682766634-cocbbbbb403iuvps1evecdk6d7phvbkf.apps.googleusercontent.com
        url: https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=${app.security.oauth2.google.callbackUrl}&prompt=consent&response_type=code&client_id=${app.security.oauth2.google.clientId}&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&access_type=offline&state=wisemapping&include_granted_scopes=true
  #  accounts:
  #    exclusion:
  #      domain:
  # Account registration options dialog
  registration:
    enabled: false
    captcha:
      enabled: false
      siteKey: some-key
      secretKey: some-secret


# Behind reverse proxy configuration
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

