
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wisemapping?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    username: wisemapping
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      platform: mysql