
spring:
  datasource:
    url: jdbc:postgresql://localhost/wisemapping
    driver-class-name: org.postgresql.Driver
    password: password
    username: wisemapping
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql